### ISSUE TITLE
Bug with the Service for connecting to Firebase

### ISSUE THREAD

**Issue by concaveNP** [concaveNP/Capstone-Project#63]
05-27 23:44:35.447 21628-21628/com.concavenp.artistrymuse E/ActivityThread: Activity com.concavenp.artistrymuse.MainActivity has leaked ServiceConnection com.concavenp.artistrymuse.MainActivity$2@946cef3 that was originally bound here
                                                                            android.app.ServiceConnectionLeaked: Activity com.concavenp.artistrymuse.MainActivity has leaked ServiceConnection com.concavenp.artistrymuse.MainActivity$2@946cef3 that was originally bound here
                                                                                at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                                at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                                at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                                at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                                at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                                at com.concavenp.artistrymuse.MainActivity.onCreate(MainActivity.java:67)
                                                                                at android.app.Activity.performCreate(Activity.java:6679)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by concaveNP** [comment]
https://www.google.com/search?q=android+checking+if+service+is+boung&rlz=1C1CHFX_enUS699US699&oq=android+checking+if+service+is+boung&aqs=chrome..69i57j0.6469j0j7&sourceid=chrome&ie=UTF-8#q=android+checking+if+service+is+bound

**Comment by concaveNP** [comment]
#76
